### ISSUE TITLE
Magic number is not correct!

### ISSUE THREAD

**Issue by dayhi** [xuedingmiaojun/wxappUnpacker#1]
```
day@DESKTOP-DO85U1M MINGW64 /d/app/weichatpojie
$ ./bingo.sh testapk/1.wxapkg
node /d/app/weichatpojie/wuWxapkg.js
Unpack file testapk/1.wxapkg...

Header info:
  firstMark: 0x56
  unknownInfo:  827149655
  infoListLength:  1489312796
  dataLength:  1346416792
  lastMark: 0xdf
D:\app\weichatpojie\wuWxapkg.js:21
    if (firstMark != 0xbe || lastMark != 0xed) throw Error("Magic number is not correct!");
                                               ^

Error: Magic number is not correct!
    at header (D:\app\weichatpojie\wuWxapkg.js:21:54)
    at D:\app\weichatpojie\wuWxapkg.js:186:44
    at D:\app\weichatpojie\wuLib.js:95:14
    at agent (D:\app\weichatpojie\wuLib.js:64:23)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)

```

如果需要提供1.wxapkg请留言

**Comment by Jerrodly** [comment]
我也遇到这种错误，子包无法解析

**Comment by xuedingmiaojun** [comment]
> ```
> day@DESKTOP-DO85U1M MINGW64 /d/app/weichatpojie
> $ ./bingo.sh testapk/1.wxapkg
> node /d/app/weichatpojie/wuWxapkg.js
> Unpack file testapk/1.wxapkg...
> 
> Header info:
>   firstMark: 0x56
>   unknownInfo:  827149655
>   infoListLength:  1489312796
>   dataLength:  1346416792
>   lastMark: 0xdf
> D:\app\weichatpojie\wuWxapkg.js:21
>     if (firstMark != 0xbe || lastMark != 0xed) throw Error("Magic number is not correct!");
>                                                ^
> 
> Error: Magic number is not correct!
>     at header (D:\app\weichatpojie\wuWxapkg.js:21:54)
>     at D:\app\weichatpojie\wuWxapkg.js:186:44
>     at D:\app\weichatpojie\wuLib.js:95:14
>     at agent (D:\app\weichatpojie\wuLib.js:64:23)
>     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
> ```
> 
> 如果需要提供1.wxapkg请留言

包发我看看吧

**Comment by LuBin1994** [comment]
我试了下，pc版微信打开的小程序的包解出来会报这个错，从模拟器里拿出来的包可以正常解

**Comment by KpLi0rn** [comment]
我也遇到了这个问题 请问您解决了吗
