### ISSUE TITLE
缺少样式等文件 求帮助

### ISSUE THREAD

**Issue by 5wcx** [xuedingmiaojun/wxappUnpacker#16]
包已上传 这个包解析少文件。比如 .jui-box 之类的css  都解析不出来。求帮助

[_669086252_19.zip](https://github.com/xuedingmiaojun/wxappUnpacker/files/5375108/_669086252_19.zip)

**Comment by 5wcx** [comment]
> 这块有异常程序没做处理。单独提取了三个文件(看看有没有缺的)的样式，文件名前面是路径，可以暂时在里面搜索一下 jui-box 相关样式粘贴到需要的文件里面
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xuedingmiaojun/wxappUnpacker" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月14日(星期三) 上午9:56 收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[xuedingmiaojun/wxappUnpacker] 缺少样式等文件 求帮助 (#16) 包已上传 这个包解析少文件。比如 .jui-box 之类的css 都解析不出来。求帮助 _669086252_19.zip — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

怎么提取？提取什么文件？可以发我吗

**Comment by xuedingmiaojun** [comment]
> > 这块有异常程序没做处理。单独提取了三个文件(看看有没有缺的)的样式，文件名前面是路径，可以暂时在里面搜索一下 jui-box 相关样式粘贴到需要的文件里面
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "xuedingmiaojun/wxappUnpacker" <[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年10月14日(星期三) 上午9:56 收件人: "xuedingmiaojun/wxappUnpacker"<[wxappUnpacker@noreply.github.com](mailto:wxappUnpacker@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: [xuedingmiaojun/wxappUnpacker] 缺少样式等文件 求帮助 (#16) 包已上传 这个包解析少文件。比如 .jui-box 之类的css 都解析不出来。求帮助 _669086252_19.zip — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 怎么提取？提取什么文件？可以发我吗

[](url)

**Comment by xuedingmiaojun** [comment]
[jui-jd-wxss.zip](https://github.com/xuedingmiaojun/wxappUnpacker/files/5390331/jui-jd-wxss.zip)
