### ISSUE TITLE
主包能解，分包解不出来

### ISSUE THREAD

**Issue by mfkwvf** [xuedingmiaojun/wxappUnpacker#20]
请教一下：主包能解，分包解析一直报：

Error: 检测到此包是分包后的子包, 请通过 -s 参数指定存放路径后重试, 如 node wuWxapkg.js -s=/xxx/xxx ./testpkg/test-pkg-sub.wxapkg
    at Array.packDone (H:\wxappUnpacker\wuWxapkg.js:176:19)
    at CntEvent.decount (H:\wxappUnpacker\wuLib.js:22:54)
    at ioLimit.runWithCb.err (H:\wxappUnpacker\wuLib.js:95:17)
    at agent (H:\wxappUnpacker\wuLib.js:66:23)
    at FSReqWrap.oncomplete (fs.js:141:20)

我执行的命令是：bingo.bat ./situ_wxapp/_-674778132_29.wxapkg [-s=../situ_wxapp/_1514036652_29，如果可以的话，我可以邮箱把包发给你试下。

-------------------------------------------
经查好看是批处理文件获取不到-s参数导致的，但是不会改批处理文件，请帮助

**Comment by xuedingmiaojun** [comment]
> 请教一下：主包能解，分包解析一直报：
> 
> Error: 检测到此包是分包后的子包, 请通过 -s 参数指定存放路径后重试, 如 node wuWxapkg.js -s=/xxx/xxx ./testpkg/test-pkg-sub.wxapkg
> at Array.packDone (H:\wxappUnpacker\wuWxapkg.js:176:19)
> at CntEvent.decount (H:\wxappUnpacker\wuLib.js:22:54)
> at ioLimit.runWithCb.err (H:\wxappUnpacker\wuLib.js:95:17)
> at agent (H:\wxappUnpacker\wuLib.js:66:23)
> at FSReqWrap.oncomplete (fs.js:141:20)
> 
> 我执行的命令是：bingo.bat ./situ_wxapp/_-674778132_29.wxapkg [-s=../situ_wxapp/_1514036652_29，如果可以的话，我可以邮箱把包发给你试下。
> 
> 经查好看是批处理文件获取不到-s参数导致的，但是不会改批处理文件，请帮助

微信搜索小程序逆向教程，有一篇文章讲这个bingo.bat的，可以参考下

**Comment by mfkwvf** [comment]
经测：linux下面解分包没有问题，windows需要修改下bat文件。

**Comment by xcodebin** [comment]
bingo.bat第十行改为node %WXAPPUNPACKER_PATH%/wuWxapkg.js %2=%3 %1
