### ISSUE TITLE
报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json

### ISSUE THREAD

**Issue by smvwvp** [xuedingmiaojun/wxappUnpacker#6]
D:\wxappUnpacker\wuLib.js:86
        if (err) throw Error("Save file error: " + err);
                 ^

Error: Save file error: Error: ENOENT: no such file or directory, open 'D:\wxappUnpacker\_-480138339_113\plugin-private:\wx2b03c6e691cd7370\plugin.json'
    at D:\wxappUnpacker\wuLib.js:86:24
    at agent (D:\wxappUnpacker\wuLib.js:64:23)
    at fs.js:1336:7

**Comment by xuedingmiaojun** [comment]
你好 可以把包发来看看嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月22日(星期三) 晚上7:34
收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6)





 
D:\wxappUnpacker\wuLib.js:86
 if (err) throw Error("Save file error: " + err);
 ^
 
Error: Save file error: Error: ENOENT: no such file or directory, open 'D:\wxappUnpacker_-480138339_113\plugin-private:\wx2b03c6e691cd7370\plugin.json'
 at D:\wxappUnpacker\wuLib.js:86:24
 at agent (D:\wxappUnpacker\wuLib.js:64:23)
 at fs.js:1336:7

**Comment by smvwvp** [comment]
请帮忙看下 大佬


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月22日(星期三) 晚上7:52
收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;;
抄送:&nbsp;"这爱、狠珍惜"<184568397@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6)





 你好 可以把包发来看看嘛 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年7月22日(星期三) 晚上7:34 
 收件人:&amp;nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6) 
 
 
 
 
 
   
 D:\wxappUnpacker\wuLib.js:86 
  if (err) throw Error("Save file error: " + err); 
  ^ 
   
 Error: Save file error: Error: ENOENT: no such file or directory, open 'D:\wxappUnpacker_-480138339_113\plugin-private:\wx2b03c6e691cd7370\plugin.json' 
  at D:\wxappUnpacker\wuLib.js:86:24 
  at agent (D:\wxappUnpacker\wuLib.js:64:23) 
  at fs.js:1336:7

**Comment by smvwvp** [comment]
大佬 ，包邮件发你了。帮看看什么情况  谢谢

**Comment by smvwvp** [comment]
大佬  我用QQ邮箱压缩后回复的，直接在这里不知道咋上传附件。。。。 我放到了百度网盘里，谢谢大佬  [链接: https://pan.baidu.com/s/1C1evTqwllxIFIlpcbb_MBg 提取码: yn9r 复制这段内容后打开百度网盘手机App，操作更方便哦](url)

**Comment by smvwvp** [comment]
收到么&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月23日(星期四) 晚上10:59
收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;;
抄送:&nbsp;"这爱、狠珍惜"<184568397@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6)





 发到哪儿了呢，没看到附件里有 
 
 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年7月23日(星期四) 晚上8:20 
 收件人:&amp;nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"СЮЭ Gang"<490599161@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6) 
 
 
 
 
 
   
 大佬 ，包邮件发你了。帮看看什么情况  谢谢

**Comment by xuedingmiaojun** [comment]
看看能不能用 附件发你了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月24日(星期五) 晚上7:24
收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;;
抄送:&nbsp;"СЮЭ Gang"<490599161@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6)





 收到么&amp;nbsp; 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年7月23日(星期四) 晚上10:59 
 收件人:&amp;nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"这爱、狠珍惜"<184568397@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6) 
 
 
 
 
 
  发到哪儿了呢，没看到附件里有  
   
   
   
   
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年7月23日(星期四) 晚上8:20  
  收件人:&amp;amp;nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"СЮЭ Gang"<490599161@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6)  
   
   
   
   
   
     
  大佬 ，包邮件发你了。帮看看什么情况  谢谢

**Comment by smvwvp** [comment]
一样没看到附件。。。。 是因为这qq邮箱不行么。。。 184568397@qq.com&nbsp; 谢谢大佬，万分感谢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月24日(星期五) 晚上7:28
收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;;
抄送:&nbsp;"这爱、狠珍惜"<184568397@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6)





 看看能不能用 附件发你了 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年7月24日(星期五) 晚上7:24 
 收件人:&amp;nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"СЮЭ Gang"<490599161@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6) 
 
 
 
 
 
  收到么&amp;amp;nbsp;  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年7月23日(星期四) 晚上10:59  
  收件人:&amp;amp;nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"这爱、狠珍惜"<184568397@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6)  
   
   
   
   
   
   发到哪儿了呢，没看到附件里有   
     
     
     
     
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年7月23日(星期四) 晚上8:20   
   收件人:&amp;amp;amp;nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"СЮЭ Gang"<490599161@qq.com&amp;amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6)   
     
     
     
     
     
       
   大佬 ，包邮件发你了。帮看看什么情况  谢谢

**Comment by xuedingmiaojun** [comment]
链接: https://pan.baidu.com/s/1HEU637hB0-zjbw0O_cFysQ 提取码: 7sbd





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月24日(星期五) 晚上7:31
收件人:&nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&gt;;
抄送:&nbsp;"СЮЭ Gang"<490599161@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6)





 一样没看到附件。。。。 是因为这qq邮箱不行么。。。 184568397@qq.com&amp;nbsp; 谢谢大佬，万分感谢。 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年7月24日(星期五) 晚上7:28 
 收件人:&amp;nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"这爱、狠珍惜"<184568397@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6) 
 
 
 
 
 
  看看能不能用 附件发你了  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年7月24日(星期五) 晚上7:24  
  收件人:&amp;amp;nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"СЮЭ Gang"<490599161@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6)  
   
   
   
   
   
   收到么&amp;amp;amp;nbsp;   
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年7月23日(星期四) 晚上10:59   
   收件人:&amp;amp;amp;nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"这爱、狠珍惜"<184568397@qq.com&amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6)   
     
     
     
     
     
    发到哪儿了呢，没看到附件里有    
       
       
       
       
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "xuedingmiaojun/wxappUnpacker"                                                                                    <notifications@github.com&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2020年7月23日(星期四) 晚上8:20    
    收件人:&amp;amp;amp;amp;nbsp;"xuedingmiaojun/wxappUnpacker"<wxappUnpacker@noreply.github.com&amp;amp;amp;amp;gt;;    
    抄送:&amp;amp;amp;amp;nbsp;"СЮЭ Gang"<490599161@qq.com&amp;amp;amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [xuedingmiaojun/wxappUnpacker] 报保存错误，试了N多小程序都一样的错误，大佬帮看下，解出来的没有app.json (#6)    
       
       
       
       
       
         
    大佬 ，包邮件发你了。帮看看什么情况  谢谢

**Comment by smvwvp** [comment]
可以了。。。这是为嘛  在自己这不行    大佬，你也用的 现在这个版本么？ 需要特别设置什么东西么？

**Comment by huaichao569** [comment]
有解决吗
