### ISSUE TITLE
Error: Save file error: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by punkvv** [xuedingmiaojun/wxappUnpacker#8]
程序执行错误信息(如果反馈是抛出异常的错误，必填):
C:\code\github\wxappUnpacker\wuLib.js:86
        if (err) throw Error("Save file error: " + err);
                 ^

Error: Save file error: Error: ENOENT: no such file or directory, open 'C:\code\github\wxappUnpacker\hc_cms\pages\index_gallery\plugin:\wxa75efa648b60994b\video.json'
    at C:\code\github\wxappUnpacker\wuLib.js:86:24
    at agent (C:\code\github\wxappUnpacker\wuLib.js:64:23)
    at fs.js:1263:7
    at FSReqCallback.oncomplete (fs.js:155:23)

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):
链接：https://pan.baidu.com/s/1DS5k4kwR7uFj4PJgonqWOQ 
提取码：l1ny

**Comment by huaichao569** [comment]
我也遇到这样的问题了，你的解决了吗
